spring:
    application:
        name: LibraryREST
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        open-in-view: true
    data:
        jdbc:
            dialect: postgresql
    mvc:
        hiddenmethod:
            filter:
                enabled: true
